#keycloak:
#  realm: test
#  host: http://test:8443

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: root
    password: 123456
    url: jdbc:h2:mem:testdb;MODE=MYSQL;DATABASE_TO_LOWER=TRUE # É possível persistir em um arquivo alterando "mem:adm_videos_test" para "file:./.h2/dev"
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true