#amqp:
#  admin:
#    auto-create: true
#  host: localhost
#  port: 5672
#  username: adm_videos
#  password: 123456
#
#keycloak:
#  realm: fc3-codeflix
#  host: http://localhost:8443

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none